#!/usr/bin/env python
# coding: utf-8

# # Vivir sin plasticos
# 
# ![imagen](https://www.sinplastico.com/4928-large_default/vivir-sin-plastico.jpg)
# 
# Estamos en plena lucha contra el cambio climático, y me quiero sumar, hacer algo más que echarme a las calles con una pancarta. Una de las formas de ralentizarlo es disminuir el consumo, y así la producción, de plástico. La basura plástica también acelera el calentamiento global, ya que al descomponerse libera metano (sí, como los pedos de vaca) y etileno, dos gases que provocan el efecto invernadero.
# 
# ## ¿Cómo eliminar los plásticos de tu día a día?
# 
# Decidimos que, para esta pequeña investigación de andar por casa, podía utilizar las cosas de plástico que ya tuviera, pero no adquirir nada nuevo. Si pedía un café en un bar y el azúcar me lo ponían en un sobrecito de plástico, me comprometía a tomarlo sin azúcar o ir a otro local; a no comprar ningún alimento que estuviera envuelto en plástico, ningún producto que tuviera un envase de poliespán. Ese era el plan y, como si estuviera a dieta y apuntara calorías, debía anotar todos mis fracasos. Para ver si, de verdad, era posible la vida sin plástico.
# Antes del experimento, me estuve preparando. Aunque podía usar mi cepillo de dientes antiguo, aproveché para tirarlo (es plástico pero no envase, ¿adónde va?, ¿a la basura normal? ¡Pues sí! Y en el contenedor gris acaban también los juguetes de plástico, las maquinillas de afeitar, los bastoncillos y discos de algodón, las toallitas húmedas y los preservativos). Fui consciente de todas las cosas que iba a tener que cambiar y estaba dispuesta a prepararme a fondo. Me acerqué a Yes Future, uno de los supermercados Zero Waste de Barcelona, de hecho, es el primero. Ya lleva dos años y desde entonces han surgido, además de supermercados ecológicos, muchas tiendas de productos a granel que colaboran con el medio ambiente animándonos a reutilizar envases. Allí venden desde cereales hasta legumbres, pasando por jabones y detergentes. Yurina González, autora de Mejor sin plástico –en mi opinión, la mejor guía básica para evitar residuos indestructibles (junto a la de Greenpeace que te puedes descargar aquí)–. González se ha tomado la molestia de compilar un directorio de algunas de las tiendas residuo cero que hay en nuestro país. No están todas las que son, pero sí que son todas las que están.
# 
# ## ¿Sirve de algo evitar los plásticos?
# 
# Sí, sirve. Incluso si en otras zonas del planeta (del Tercer Mundo, pero también del primero) no se planteen que exista un problema: lo hay y, sin creernos Juana de Arco, está en nuestras manos reducir el consumo de plástico sin que sea un esfuerzo inabordable. Sigue en lo que puedas las tres erres que pregona el movimiento Zero Waste:
# Rechaza lo que no necesitas: Es un grito en contra del consumismo. Yo lo que hago es darme premios. No soy de las que gasta en ropa, pero adoro los zapatos. Apenas me compro nada, pero cuando lo hago, son zapatos buenos, muy buenos. No es que me calce Blahnik, pero sí Doc Martens o El Naturalista. Menos ropa, pero de mejor calidad.
# Reutiliza lo que tienes: Ese tupper de plástico, no lo tires. Llévatelo al mercado (o al súper) y que te lo llenen del producto de tu elección: hamburguesas, lentejas cocidas, uvas, lo que sea. La primera vez da palo, luego ya no.
# Recicla todo lo que no puedes ni rechazar ni reutilizar: Circulan miles de leyendas urbanas sobre que lo que separas y te molestas en llevar al contenedor luego se junta en los vertederos y tu esfuerzo no sirve para nada. No es cierto. Y además, generas puestos de trabajo, porque el proceso de reciclaje de residuos necesita personas que recojan los distintos materiales y los clasifiquen. En España disponemos de Ecovidrio, gestión del vidrio, y Ecoembes, que se ocupa de los plásticos, latas y briks. Si tienes dudas de qué va a qué contenedor, aquí tienes unas pautas. Ambas son empresas sin ánimo de lucro.
# 
# 
# ## Los fracasos y el éxito del experimento
# 
# No puedo acabar mi semana sin comentar los fracasos. Tuve que hacer un viaje y me olvidé las pinzas de depilar en casa. Prueba a comprar unas pinzas, un cortauñas, un boli que no venga en su aislante blíster, con su suculenta ración de plástico. En la sala Club de Renfe, rellené mi botella con agua mineral, pero no pude tomar ni galletas, ni plumcake, ni patatas fritas, ni siquiera unos míseros cacahuetes. Todo va envuelto en plástico. La crema solar aún no la venden a granel, que yo sepa, ni las hidratantes corporales. O las medicinas. Ni una triste aspirina viene fuera de su envase. Y cada vez que miro el móvil, veo que no podré nunca prescindir de él, ni de mi ordenador, que además de plástico, contienen oro, wolframio, estaño y tantalio (que se saca del coltán), los llamados "minerales de sangre" extraídos de zonas en guerra como la República Democrática del Congo o Sudáfrica.
# Sin embargo, por desmoralizante que sea la situación, tener en nuestra mano la oportunidad de hacer algo, da un gran poder, o al menos cierta satisfacción. No se trata de condescendencia en plan "mira que buena soy que llevo siempre mis bolsas de algodón", sino más bien la sensación de triunfo por la rebeldía de no pasar por el aro del consumismo absurdo, de eliminar lo superfluo. "A mí me ha servido", me digo, mientras miro con añoranza esos briks de gazpacho que han sido hasta hace dos días la base de mi alimentación. No, si con este nuevo paradigma, a lo mejor hasta aprendo a cocinar.
